export const GET_PRODUCTS_CATALOG_REQUEST = 'GET_PRODUCTS_CATALOG_REQUEST';
export const GET_PRODUCTS_CATALOG_SUCCESS = 'GET_PRODUCTS_CATALOG_SUCCESS';
export const GET_PRODUCTS_CATALOG_FAIL = 'GET_PRODUCTS_CATALOG_FAIL';
